#%RAML 1.0 Extension
usage: Adds dotnet SDK extended functionality
extends: api.raml
annotationTypes:
  csharp-implements:
    type: string
    allowedTargets: TypeDeclaration
  csharp-extends:
    type: string
    allowedTargets: TypeDeclaration

types:
  OrderUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IOrderUpdate, IOrderUpdateAction>'
  OrderUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IOrderUpdateAction>'
  PaymentUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IPaymentUpdate, IPaymentUpdateAction>'
  PaymentUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IPaymentUpdateAction>'
  ProductUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IProductUpdate, IProductUpdateAction>'
  ProductUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IProductUpdateAction>'
  ProductDiscountUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IProductDiscountUpdate, IProductDiscountUpdateAction>'
  ProductDiscountUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IProductDiscountUpdateAction>'
  ProductSelectionUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IProductSelectionUpdate, IProductSelectionUpdateAction>'
  ProductSelectionUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IProductSelectionUpdateAction>'
  ProductTypeUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IProductTypeUpdate, IProductTypeUpdateAction>'
  ProductTypeUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IProductTypeUpdateAction>'
  ProjectUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IProjectUpdate, IProjectUpdateAction>'
  ProjectUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IProjectUpdateAction>'
  ReviewUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IReviewUpdate, IReviewUpdateAction>'
  ReviewUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IReviewUpdateAction>'
  ShippingMethodUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IShippingMethodUpdate, IShippingMethodUpdateAction>'
  ShippingMethodUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IShippingMethodUpdateAction>'
  ShoppingListUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IShoppingListUpdate, IShoppingListUpdateAction>'
  ShoppingListUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IShoppingListUpdateAction>'
  StateUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IStateUpdate, IStateUpdateAction>'
  StateUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IStateUpdateAction>'
  StoreUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IStoreUpdate, IStoreUpdateAction>'
  StoreUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IStoreUpdateAction>'
  SubscriptionUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<ISubscriptionUpdate, ISubscriptionUpdateAction>'
  SubscriptionUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<ISubscriptionUpdateAction>'
  TaxCategoryUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<ITaxCategoryUpdate, ITaxCategoryUpdateAction>'
  TaxCategoryUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<ITaxCategoryUpdateAction>'
  TypeUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<ITypeUpdate, ITypeUpdateAction>'
  TypeUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<ITypeUpdateAction>'
  ZoneUpdate:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdate<IZoneUpdate, IZoneUpdateAction>'
  ZoneUpdateAction:
    (csharp-extends): 'commercetools.Sdk.Api.Models.IResourceUpdateAction<IZoneUpdateAction>'
/{projectKey}:
  /cart-discounts:
    get:
      (csharp-implements):
       'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyCartDiscountsGet,
       commercetools.Sdk.Api.Models.CartDiscounts.ICartDiscountPagedQueryResponse>'
  /carts:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyCartsGet,
        commercetools.Sdk.Api.Models.Carts.ICartPagedQueryResponse>'
  /categories:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyCategoriesGet,
        commercetools.Sdk.Api.Models.Categories.ICategoryPagedQueryResponse>'
  /channels:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyChannelsGet,
        commercetools.Sdk.Api.Models.Channels.IChannelPagedQueryResponse>'
  /custom-objects:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyCustomObjectsGet,
        commercetools.Sdk.Api.Models.CustomObjects.ICustomObjectPagedQueryResponse>'
  /customer-groups:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyCustomerGroupsGet,
        commercetools.Sdk.Api.Models.CustomerGroups.ICustomerGroupPagedQueryResponse>'
  /customers:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyCustomersGet,
        commercetools.Sdk.Api.Models.Customers.ICustomerPagedQueryResponse>'
  /discount-codes:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyDiscountCodesGet,
        commercetools.Sdk.Api.Models.DiscountCodes.IDiscountCodePagedQueryResponse>'
  /extensions:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyExtensionsGet,
        commercetools.Sdk.Api.Models.Extensions.IExtensionPagedQueryResponse>'
  /in-store/key={storeKey}:
    /me:
      /shopping-lists:
        get:
          (csharp-implements):
            'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyInStoreKeyByStoreKeyMeShoppingListsGet,
            commercetools.Sdk.Api.Models.ShoppingLists.IShoppingListPagedQueryResponse>'
    /shopping-lists:
      get:
        (csharp-implements):
          'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyInStoreKeyByStoreKeyShoppingListsGet,
          commercetools.Sdk.Api.Models.ShoppingLists.IShoppingListPagedQueryResponse>'
  /inventory:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyInventoryGet,
        commercetools.Sdk.Api.Models.Inventories.IInventoryPagedQueryResponse>'
  /messages:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyMessagesGet,
        commercetools.Sdk.Api.Models.Messages.IMessagePagedQueryResponse>'
  /orders:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyOrdersGet,
        commercetools.Sdk.Api.Models.Orders.IOrderPagedQueryResponse>'
    /edits:
      get:
        (csharp-implements):
          'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyOrdersEditsGet,
          commercetools.Sdk.Api.Models.OrderEdits.IOrderEditPagedQueryResponse>'
  /payments:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyPaymentsGet,
        commercetools.Sdk.Api.Models.Payments.IPaymentPagedQueryResponse>'
  /product-discounts:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyProductDiscountsGet,
        commercetools.Sdk.Api.Models.ProductDiscounts.IProductDiscountPagedQueryResponse>'
  /product-projections:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyProductProjectionsGet,
        commercetools.Sdk.Api.Models.Products.IProductProjectionPagedQueryResponse>'
  /product-types:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyProductTypesGet,
        commercetools.Sdk.Api.Models.ProductTypes.IProductTypePagedQueryResponse>'
  /products:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyProductsGet,
        commercetools.Sdk.Api.Models.Products.IProductPagedQueryResponse>'
  /reviews:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyReviewsGet,
        commercetools.Sdk.Api.Models.Reviews.IReviewPagedQueryResponse>'
  /shipping-methods:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyShippingMethodsGet,
        commercetools.Sdk.Api.Models.ShippingMethods.IShippingMethodPagedQueryResponse>'
  /shopping-lists:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyShoppingListsGet,
        commercetools.Sdk.Api.Models.ShoppingLists.IShoppingListPagedQueryResponse>'
  /standalone-prices:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyStandalonePricesGet,
        commercetools.Sdk.Api.Models.StandalonePrices.IStandalonePricePagedQueryResponse>'
  /states:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyStatesGet,
        commercetools.Sdk.Api.Models.States.IStatePagedQueryResponse>'
  /stores:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyStoresGet,
        commercetools.Sdk.Api.Models.Stores.IStorePagedQueryResponse>'
  /subscriptions:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeySubscriptionsGet,
        commercetools.Sdk.Api.Models.Subscriptions.ISubscriptionPagedQueryResponse>'
  /tax-categories:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyTaxCategoriesGet,
        commercetools.Sdk.Api.Models.TaxCategories.ITaxCategoryPagedQueryResponse>'
  /types:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyTypesGet,
        commercetools.Sdk.Api.Models.Types.ITypePagedQueryResponse>'
  /zones:
    get:
      (csharp-implements):
        'commercetools.Sdk.Api.Models.IPagedQueryResourceRequest<ByProjectKeyZonesGet,
        commercetools.Sdk.Api.Models.Zones.IZonePagedQueryResponse>'