# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  otlp/2:
    endpoint: ${NEW_RELIC_OTLP_ENDPOINT}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      exporters: [otlp, logging, spanmetrics, otlp/2]
    metrics:
      exporters: [prometheus, logging, otlp/2]
    logs:
      exporters: [logging, otlp/2]